# Generated by Django 2.1.7 on 2019-03-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0003_auto_20190319_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iso',
            old_name='name',
            new_name='iso',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='states',
            old_name='name',
            new_name='states',
        ),
    ]
