# Generated by Django 2.1.7 on 2019-03-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0004_auto_20190319_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iso',
            old_name='iso',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='states',
            old_name='states',
            new_name='name',
        ),
    ]
