# Generated by Django 2.1.7 on 2019-03-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0005_auto_20190319_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
