# Generated by Django 2.1.7 on 2019-03-01 01:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')])),
                ('weight', models.PositiveIntegerField()),
                ('foods', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Kind must be greater than 1 character')])),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Kind'),
        ),
    ]
